Extract image hash for later display in container
lsst-sqre/nublado2 pull request #37
Opened 2021-03-29 21:45 UTC by athornton

Here's some output from a container, showing that I am running "recommended" but I have the resolved tag and its hash in the environment, as well as in the file mounted into the container from the configmap.

```
[athornto@jupyter-athornto ~]$ env | grep recommended; env | grep ^IMAGE; for i in $(env | grep ^IMAGE | cut -d '=' -f 1); do fn=/opt/lsst/software/jupyterlab/environment/$i; echo "$fn: "; cat $fn; echo -e "\n----"; done
JUPYTER_IMAGE_SPEC=registry.hub.docker.com/lsstsqre/sciplat-lab:recommended
JUPYTER_IMAGE=registry.hub.docker.com/lsstsqre/sciplat-lab:recommended
IMAGE_NAME=sciplat-lab
IMAGE_HASH=sha256:419c4b7e14603711b25fa9e0569460a753c4b2449fe275bb5f89743b01794a30
IMAGE_TAG=w_2021_13
/opt/lsst/software/jupyterlab/environment/IMAGE_NAME: 
sciplat-lab
----
/opt/lsst/software/jupyterlab/environment/IMAGE_HASH: 
sha256:419c4b7e14603711b25fa9e0569460a753c4b2449fe275bb5f89743b01794a30
----
/opt/lsst/software/jupyterlab/environment/IMAGE_TAG: 
w_2021_13
----
```

2021-03-29 22:12 UTC, cbanek requested changes

2021-03-29 22:12 UTC, cbanek commented on src/nublado2/resourcemgr.py
> +            if img_tag == "recommended":
Get rid of this part.  There should be no mention of the word recommended in nublado

2021-03-29 22:12 UTC, cbanek commented on src/nublado2/resourcemgr.py
> +            (repo, img_name, img_tag, img_hash) = await self._split_spec(spec)
Earlier on you add the image hash after the name with a pipe.  Do the same for img_tag.  for image_name just use the full URL.  Then get rid of the _split_spec function.

Only split strings you make yourself here in this code, don't try to parse any docker URLs.

2021-03-29 22:12 UTC, cbanek commented on src/nublado2/resourcemgr.py
> +    async def _split_spec(self, spec: str) -> Tuple[str, str, str, str]:
Get rid of this function.  Also, it probably doesn't need to be async.

2021-03-29 22:12 UTC, cbanek commented on src/nublado2/options.py
> +     id="{{ i.name }}" value="{{ i.image_url }}|{{ i.image_hash }}"
Either put the name here or use the name field returned from here for the name, but don't parse the URL.

2021-03-29 22:12 UTC, cbanek commented on src/nublado2/hooks.py
> +        image_spec = options["image"][0]
if we're packing more things in here, it's not really an image anymore.  Maybe we should call this image_info or something?  We should probably make a simple container class for it with the parsing logic attached.

2021-03-29 22:13 UTC, cbanek commented on src/nublado2/options.py
> +     id="{{ i.name }}" value="{{ i.image_url }}|{{ i.image_hash }}"
It is okay to concat some things here, although it probably makes it more obvious what is going on if we have a type and then turn to a string rather than doing it in the templating part.

2021-03-29 22:39 UTC, athornton commented on src/nublado2/hooks.py
> +        image_spec = options["image"][0]
As far as Python is concerned it's still a string, and if you take it from the dropdown, the hash is not present, so I don't think a class is worthwhile.  Calling it image_info seems like a good idea.

2021-03-29 22:49 UTC, cbanek commented on src/nublado2/hooks.py
> +        image_spec = options["image"][0]
It's a string, with some fields, and a way of packing it.  It's useful to put all that together in a class.  Please make a class.

2021-03-29 22:50 UTC, cbanek commented on src/nublado2/hooks.py
> +        image_spec = options["image"][0]
The constructor will take the initial string from the form.  Then you can parse it out into properties.

2021-03-29 22:55 UTC, cbanek commented on src/nublado2/resourcemgr.py
> +            if image_info != "image_tag":
maybe just put all the hashes after all the images?

2021-03-31 18:40 UTC, athornton commented on src/nublado2/resourcemgr.py
> +            (repo, img_name, img_tag, img_hash) = await self._split_spec(spec)
Moved to ImageInfo class

2021-03-31 18:40 UTC, athornton commented on src/nublado2/resourcemgr.py
> +    async def _split_spec(self, spec: str) -> Tuple[str, str, str, str]:
Functionality moved to ImageInfo class

2021-03-31 18:41 UTC, athornton commented on src/nublado2/resourcemgr.py
> +            if image_info != "image_tag":
Both forms (list and dropdown) now return strings in same format, which is (I think) what you were asking for.

2021-03-31 21:41 UTC, cbanek commented on src/nublado2/resourcemgr.py
> +                "image_desc": img_desc,
"image_info": img_info

2021-03-31 21:42 UTC, cbanek commented on dev-values.yaml
> +        IMAGE_TAG:  "{{ image_tag }}"
{{ image_info.tag() }}
{{ image_info.image_hash() }}
{{ image_info.image_desc() }}

2021-03-31 21:44 UTC, cbanek commented on src/nublado2/resourcemgr.py
> +        self.image_tag = self.image_spec.split(":")[-1]
def from_cachemachine_response(cachemachine_info) -> ImageInfo

def from_packaged_string(str) -> ImageInfo

from functions set up properties, only ones who can write to private field
Read only properties
spec
desc
hash
tag

2021-04-01 02:49 UTC, athornton commented on src/nublado2/resourcemgr.py
> +                "image_desc": img_desc,
Done

2021-04-01 02:49 UTC, athornton commented on dev-values.yaml
> +        IMAGE_TAG:  "{{ image_tag }}"
Done

2021-04-01 02:56 UTC, athornton commented on src/nublado2/resourcemgr.py
> +        self.image_tag = self.image_spec.split(":")[-1]
I don't see how to make a dataclass property write-once.  Since we're not doing it in init(), they have to be mutable after object creation.

This https://stackoverflow.com/questions/61237131/how-to-make-attribute-in-dataclass-read-only would kinda work, but I'd have to write __init__() and a repr, which seems to break the whole point of making it a dataclass.

I want to keep it as a dataclass, because I get __init__() and a nice repr for free, and it basically is a dataclass.  My current approach has been to just leave the fields mutable and not mutate them (hence the reason for the creating-the-fake-entry function...it's not in the class, but at least it's in the same source file that's the only place I'm screwing with the fields directly).  The other direction I could go is to make __init__() bivalent and accept either a cachemachine entry or a packed string, figure out which one I got, assert all the stuff I need to to make sure it's a legal entry or string, and then set the fields at construction time.

If you'd prefer that one, or you know a way to make the fields write-once and not gross, let me know.

2021-04-01 22:13 UTC, athornton commented on src/nublado2/resourcemgr.py
> +        self.image_tag = self.image_spec.split(":")[-1]
Now a frozen dataclass with classmethods.

2021-04-01 22:35 UTC, jonathansick approved these changes
Looks good from my perspective.

2021-04-01 22:35 UTC, jonathansick commented on src/nublado2/imageinfo.py
> +    """display_name is a human-readable description of the image.
Just fyi I think that docstrings for attributes go below the attribute, rather than above.

2021-04-01 22:35 UTC, jonathansick commented on src/nublado2/imageinfo.py
> +        return ImageInfo(
```suggestion
        return cls(
```

Same this, but it helps in case there's some subclassing going on.

2021-04-01 22:35 UTC, jonathansick commented on src/nublado2/imageinfo.py
> +        assert len(fields) == 3, (
Is there no change this'll happen in runtime? If there is, I'd use an exception of some sort like RuntimeError

2021-04-01 22:35 UTC, jonathansick commented on src/nublado2/imageinfo.py
> +        return ImageInfo(
```suggestion
        return cls(
```

2021-04-01 22:43 UTC, athornton commented on src/nublado2/imageinfo.py
> +    """display_name is a human-readable description of the image.
OK

2021-04-01 22:43 UTC, athornton commented on src/nublado2/imageinfo.py
> +        return ImageInfo(
OK

2021-04-01 22:43 UTC, athornton commented on src/nublado2/imageinfo.py
> +        assert len(fields) == 3, (
OK.

2021-04-01 22:43 UTC, athornton commented on src/nublado2/imageinfo.py
> +        return ImageInfo(
OK

2021-04-01 22:45 UTC, cbanek approved these changes

2021-04-01 23:15 UTC, merged